target("1.6-shaders-ex2")
    set_kind("binary")
    add_rules("utils.bin2c", {extensions = {".fs", ".vs"}})
    add_files("shader.*")
    add_files("main.cpp")
    add_packages("glfw", "glad", "glm")
