target("9-ssao")
    set_kind("binary")
    add_rules("utils.bin2c", {extensions = {".fs", ".vs"}})
    add_files("*.vs", "*.fs")
    add_files("main.cpp")
    add_packages("glfw", "glad", "stb", "glm", "assimp")
